### ISSUE TITLE
It wont scroll

### ISSUE THREAD

**Issue by Sophia-Villamayor** [Sophia-Villamayor/more-than-just-datum#2]
@muxlowc - Thank you so much for your recent help :)

However, I encountered another problem unfortunately. I noticed when I go to smaller screen sizes, the table isn't scrollable. I ensured I selected all in my modules, and added the class "scrollable" within the tag, so I'm not too sure on what went wrong. Sorry to bother!

@mackenzierose

**Comment by muxlowc** [comment]
@Sophia-Villamayor in order for it to scroll, you'll need to tell your table to not get any smaller than a certain size.

.table-wrapper table {
  min-width: 45em;
}

Hope that helps?
